version: 2
jobs:
  build:
    working_directory: ~/example-python
    docker:
      - image: circleci/python:3.7    
    steps:
      - checkout
      - run:
          command:
            sudo pip install --upgrade pip
      - run:
          command:
            sudo pip install coverage
      - run:
          command:
            coverage run tests.py && coverage report
            
      - store_artifacts:
          path: test-results
