version: 2
jobs:
  build:
    working_directory: ~/example-python
    docker:
      - image: circleci/python:3.6.4     
    steps:
      - checkout
      - run:
        name: Setup testing environment
        command:
          pip install coverage
      - run:
        name: Running Tests
        command:
          coverage run tests.py
