version: 2
jobs:
  build:
    working_directory: ~/example-python
    docker:
      - image: circleci/python:3.7    
    steps:
      - checkout
      - run:
          command:
            pip install --upgrade pip
      - run:
          command:
            pip install coverage
      - run:
          command:
            coverage run tests.py
