version: 2
jobs:
  build:
    working_directory: ~/example-python
    docker:
      - image: circleci/python:3.7    
    steps:
      - checkout
      - run:
          command:
            sudo pip install --upgrade pip
      - run: mkdir test-reports
      - run:
          command:
            sudo pip install coverage
      - run:
          command:
            coverage run tests.py && coverage report && coverage xml -o test-reports/coverage.xml
      - run:
          command:
            coverage report && coverage xml -o test-reports/coverage.xml
      - run:
          command:
            coverage xml
      - store_artifacts:
          path: test-reports
          destination: test-reports
          
      - store_artifacts:
          path: coverage
          destination: coverage
